---
#
# Pipeline:
# automated build and deploy this project
# by: Isca
#

stages:
  - coverage
  - build

variables:
  #IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  #CI_DEBUG_TRACE: "true"
 
coverage:
  image: golang:1.12-alpine3.9
  stage: coverage
  tags:
    - docker
  only:
    - master
  script:
    - "apk add --no-cache git build-base"
    - "make coverage"
